# Numpy libaray

In [1]:
import numpy as np

In [2]:
#covert List to array
list1=[2,3,4,6,8,9,4]

In [3]:
#its 1D array
arr1=np.array(list1)
print(arr1,"\n",arr1.__class__) 

[2 3 4 6 8 9 4] 
 <class 'numpy.ndarray'>


In [4]:
#its 2D array
arr2=np.array([[23,65,78,54,89,34],[87,89,32,45,33,67]])
arr2
print(arr2)

[[23 65 78 54 89 34]
 [87 89 32 45 33 67]]


In [5]:
#its also 2D array
arr3=np.array([[4,8,9,4],[6,9,4,2],[6,2,1,0],[3,9,7,6]]) # its always 2d array does not matter how many list there in present
arr3
print(arr3)

[[4 8 9 4]
 [6 9 4 2]
 [6 2 1 0]
 [3 9 7 6]]


In [6]:
#check All Arrays Dimenssion
print(f"Dimenssion of arr1 : {arr1.ndim}D")
print(f"Dimenssion of arr2 : {arr2.ndim}D")
print(f"Dimenssion of arr3 : {arr3.ndim}D")

Dimenssion of arr1 : 1D
Dimenssion of arr2 : 2D
Dimenssion of arr3 : 2D


In [7]:
#Check There Shapes or (ROW x COLUMN)
print('Shapes of arr1 : ',arr1.shape)
print('Shapes of arr2 : ',arr2.shape) 
print('Shapes of arr3 : ',arr3.shape)

Shapes of arr1 :  (7,)
Shapes of arr2 :  (2, 6)
Shapes of arr3 :  (4, 4)


In [8]:
# its 3D Array does not matter how many list there
arr4=np.array([[[2,3,4,8],[9,5,3,6],[7,4,6,3]],[[2,1,0,2],[4,9,8,6],[8,9,3,2]]])
arr4

array([[[2, 3, 4, 8],
        [9, 5, 3, 6],
        [7, 4, 6, 3]],

       [[2, 1, 0, 2],
        [4, 9, 8, 6],
        [8, 9, 3, 2]]])

In [9]:
arr5=np.array([[[2,3,4,8],[9,5,3,6],[7,4,6,3]],[[2,1,0,2],[4,9,8,6],[9,9,3,8]],[[7,1,0,7],[0,9,8,0],[9,4,6,7]]])
arr5

array([[[2, 3, 4, 8],
        [9, 5, 3, 6],
        [7, 4, 6, 3]],

       [[2, 1, 0, 2],
        [4, 9, 8, 6],
        [9, 9, 3, 8]],

       [[7, 1, 0, 7],
        [0, 9, 8, 0],
        [9, 4, 6, 7]]])

In [10]:
#check 3D Array's Dimenssion
print(f'Dimenssion of arr4 : {arr4.ndim}D') 
print(f'Dimenssion of arr5 : {arr5.ndim}D')

Dimenssion of arr4 : 3D
Dimenssion of arr5 : 3D


In [11]:
#Check 3D Shapes or ( NoOfMatrix , EachROW , EachCOLUMN )
print('Shapes of arr4 : ',arr4.shape)
print('Shapes of arr5 : ',arr5.shape) 

Shapes of arr4 :  (2, 3, 4)
Shapes of arr5 :  (3, 3, 4)


In [12]:
#full fucntions
fullfun_num=np.full((3,4),34) # you type any number/string of array and also 3x4 matrox form
print(fullfun_num)
fullfun_str=np.full((4,4),'python') 
print("\n",fullfun_str)

[[34 34 34 34]
 [34 34 34 34]
 [34 34 34 34]]

 [['python' 'python' 'python' 'python']
 ['python' 'python' 'python' 'python']
 ['python' 'python' 'python' 'python']
 ['python' 'python' 'python' 'python']]


In [13]:
#arange funncation excatly work like range fucntion python
arr6=np.arange(10,21,2) #arange(start,end,diffrence) , there end is exclusive
arr6

array([10, 12, 14, 16, 18, 20])

In [14]:
arr6=np.arange(15,0,-1)
arr6

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [15]:
#linspace
arr7=np.linspace(10,20,15, dtype=int) # it have inclusive and it diveded with 15 equal parts
arr7
#logic behind dived equal parts b/w 10 to 20
#(20-10)/15-1 = 10/14 =0.71428571 and just add this number with 10 until we will not got 20 

array([10, 10, 11, 12, 12, 13, 14, 15, 15, 16, 17, 17, 18, 19, 20])

In [16]:
#covert arr7 array into matrix
mat1=arr7.reshape((3,5)) # by default its column wise show not row wise
mat1

array([[10, 10, 11, 12, 12],
       [13, 14, 15, 15, 16],
       [17, 17, 18, 19, 20]])

In [17]:
mat1=arr7.reshape((3,5),order='F') # now its row wise show not column wise
mat1

array([[10, 12, 14, 16, 18],
       [10, 12, 15, 17, 19],
       [11, 13, 15, 17, 20]])

In [18]:
#covert again matrix to array
mat1_to_arr=mat1.flatten()
mat1_to_arr

array([10, 12, 14, 16, 18, 10, 12, 15, 17, 19, 11, 13, 15, 17, 20])

In [19]:
#show unique values from array
unqarr1=np.array([[2,2,6],[7,8,7]],dtype=int)
unqarr1=np.unique(unqarr1)
unqarr1

array([2, 6, 7, 8])

In [20]:
#concatinate two or more arrays
arr8=np.linspace(10,19,10,dtype=int)
arr9=np.linspace(20,29,10,dtype=int)
print(arr8,"\n",arr9)
concat=np.concatenate((arr9,arr8)) # you pass with list or tuple
print("\nConcatenate Above Array\n",concat)

[10 11 12 13 14 15 16 17 18 19] 
 [20 21 22 23 24 25 26 27 28 29]

Concatenate Above Array
 [20 21 22 23 24 25 26 27 28 29 10 11 12 13 14 15 16 17 18 19]


In [21]:
#COLUMN must be same but ROW may be diffrent also rowxcolumn must be same 
mm1=arr8.reshape((5,2))
mm2=arr9.reshape((5,2))
concat=np.concatenate([mm1,mm2])
print(concat.shape)
concat

(10, 2)


array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [22]:
#convert array to list
l1=mm1.tolist()
print(l1.__class__,"\n",l1)

<class 'list'> 
 [[10, 11], [12, 13], [14, 15], [16, 17], [18, 19]]


In [23]:
#random number geberate into array
arr10=np.random.randint(1,11,8) # (start,end,diffrence), end is exclusive
arr10

array([7, 8, 6, 5, 5, 8, 6, 1])

In [24]:
#indexing acces like in python with array
print(arr10[0],"\n",arr10[-1],"\n",arr10[-3])
print(arr10[:3],"\n",arr10[5:],"\n",arr10[2:6],"\n",arr10[2:-3])

7 
 1 
 8
[7 8 6] 
 [8 6 1] 
 [6 5 5 8] 
 [6 5 5]


In [25]:
#arr5 is 3D matrix on top where we created
arr5
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[0][2],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[7 4 6 3] 



In [26]:
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[1][2],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[9 9 3 8] 



In [27]:
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[2][0][:3],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[7 1 0] 



In [28]:
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[1][0][:-1],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[2 1 0] 



In [30]:
# vstack , Hstack and column_stack

In [32]:
arr11=np.array([[2,5,7],[3,8,0],[4,7,1]])
arr12=np.array([[5,8,4],[5,8,1],[9,9,3]])
print(arr11,"\n\n",arr12) 

[[2 5 7]
 [3 8 0]
 [4 7 1]] 

 [[5 8 4]
 [5 8 1]
 [9 9 3]]


In [37]:
chnage=np.vstack([arr11,arr12])
chnage

array([[2, 5, 7],
       [3, 8, 0],
       [4, 7, 1],
       [5, 8, 4],
       [5, 8, 1],
       [9, 9, 3]])

In [38]:
chnage=np.hstack([arr11,arr12])
chnage

array([[2, 5, 7, 5, 8, 4],
       [3, 8, 0, 5, 8, 1],
       [4, 7, 1, 9, 9, 3]])

In [39]:
chnage=np.column_stack([arr11,arr12])
chnage

array([[2, 5, 7, 5, 8, 4],
       [3, 8, 0, 5, 8, 1],
       [4, 7, 1, 9, 9, 3]])

In [40]:
#intersect_1D , setdiff_1D

In [41]:
arr13=np.array([21,23,46,78,45,34,90,76])
arr14=np.array([34,67,23,78,89,56,90,76])

In [43]:
#it shows intresecting point or comman values
np.intersect1d(arr13,arr14)

array([23, 34, 76, 78, 90])

In [45]:
# it shows not repeated values or not comman value
np.setdiff1d(arr13,arr14) # arr13's non-comman values show only

array([21, 45, 46])

In [47]:
# it shows not repeated values or not comman value
np.setdiff1d(arr14,arr13) # arr14's non-comman values show only

array([56, 67, 89])

In [49]:
# Array Arithmetics

In [51]:
print("Array1 : ",arr13,"\n\nArray2 :",arr14) 

Array1 :  [21 23 46 78 45 34 90 76] 

Array2 : [34 67 23 78 89 56 90 76]


In [62]:
print("Sum is : ",np.sum((arr13,arr14)))
print("Sum of axis=0 : ",np.sum((arr13,arr14),axis=0)) # two array added with row wise or vertically
print("Sum of axis=1 : ",np.sum((arr13,arr14),axis=1)) # two array added with column wise or horizontaly 

Sum is :  926
Sum of axis=0 :  [ 55  90  69 156 134  90 180 152]
Sum of axis=1 :  [413 513]


In [68]:
#you can add, multply ,divide and subtarct  with elemnet of specfic array
print("Arr : ",arr14 )
print(" +5 : ",arr14+5 )
print(" *3 : ",arr14*3 )
print(" -1 : ",arr14-1 )
print(" /2 : ",arr14/2 )
print("//3 : ",arr14//3 )
print("**2 : ",arr14**2 )

Arr :  [34 67 23 78 89 56 90 76]
 +5 :  [39 72 28 83 94 61 95 81]
 *3 :  [102 201  69 234 267 168 270 228]
 -1 :  [33 66 22 77 88 55 89 75]
 /2 :  [17.  33.5 11.5 39.  44.5 28.  45.  38. ]
//3 :  [11 22  7 26 29 18 30 25]
**2 :  [1156 4489  529 6084 7921 3136 8100 5776]


In [71]:
# or you can use this also
print(" - : ",arr13-arr14)
print(" + : ",arr13+arr14)
print(" * : ",arr13*arr14)
print("// : ",arr13//arr14)
print(" / : ",arr13/arr14)

 - :  [-13 -44  23   0 -44 -22   0   0]
 + :  [ 55  90  69 156 134  90 180 152]
 * :  [ 714 1541 1058 6084 4005 1904 8100 5776]
// :  [0 0 2 1 0 0 1 1]
 / :  [0.61764706 0.34328358 2.         1.         0.50561798 0.60714286
 1.         1.        ]


In [72]:
#save and file loadgit

In [76]:
#save array like a file
# mt1=np.array([arr13,arr14])
# np.save('myfilename.npy',mt1)

In [79]:
#use this file myfilename.npy or load file
# usefile=np.load('myfilename.npy')
# print(usefile)