# Numpy libaray

In [1]:
import numpy as np

In [7]:
#covert List to array
list1=[2,3,4,6,8,9,4]

In [20]:
#its 1D array
arr1=np.array(list1)
print(arr1,"\n",arr1.__class__) 

[2 3 4 6 8 9 4] 
 <class 'numpy.ndarray'>


In [19]:
#its 2D array
arr2=np.array([[23,65,78,54,89,34],[87,89,32,45,33,67]])
arr2
print(arr2)

[[23 65 78 54 89 34]
 [87 89 32 45 33 67]]


In [24]:
#its also 2D array
arr3=np.array([[4,8,9,4],[6,9,4,2],[6,2,1,0],[3,9,7,6]]) # its always 2d array does not matter how many list there in present
arr3
print(arr3)

[[4 8 9 4]
 [6 9 4 2]
 [6 2 1 0]
 [3 9 7 6]]


In [63]:
#check All Arrays Dimenssion
print(f"Dimenssion of arr1 : {arr1.ndim}D")
print(f"Dimenssion of arr2 : {arr2.ndim}D")
print(f"Dimenssion of arr3 : {arr3.ndim}D")

Dimenssion of arr1 : 1D
Dimenssion of arr2 : 2D
Dimenssion of arr3 : 2D


In [28]:
#Check There Shapes or (ROW x COLUMN)
print('Shapes of arr1 : ',arr1.shape)
print('Shapes of arr2 : ',arr2.shape) 
print('Shapes of arr3 : ',arr3.shape)

Shapes of arr1 :  (7,)
Shapes of arr2 :  (2, 6)
Shapes of arr3 :  (4, 4)


In [44]:
# its 3D Array does not matter how many list there
arr4=np.array([[[2,3,4,8],[9,5,3,6],[7,4,6,3]],[[2,1,0,2],[4,9,8,6],[8,9,3,2]]])
arr4

array([[[2, 3, 4, 8],
        [9, 5, 3, 6],
        [7, 4, 6, 3]],

       [[2, 1, 0, 2],
        [4, 9, 8, 6],
        [8, 9, 3, 2]]])

In [46]:
arr5=np.array([[[2,3,4,8],[9,5,3,6],[7,4,6,3]],[[2,1,0,2],[4,9,8,6],[9,9,3,8]],[[7,1,0,7],[0,9,8,0],[9,4,6,7]]])
arr5

array([[[2, 3, 4, 8],
        [9, 5, 3, 6],
        [7, 4, 6, 3]],

       [[2, 1, 0, 2],
        [4, 9, 8, 6],
        [9, 9, 3, 8]],

       [[7, 1, 0, 7],
        [0, 9, 8, 0],
        [9, 4, 6, 7]]])

In [62]:
#check 3D Array's Dimenssion
print(f'Dimenssion of arr4 : {arr4.ndim}D') 
print(f'Dimenssion of arr5 : {arr5.ndim}D')

Dimenssion of arr4 : 3D
Dimenssion of arr5 : 3D


In [47]:
#Check 3D Shapes or ( NoOfMatrix , EachROW , EachCOLUMN )
print('Shapes of arr4 : ',arr4.shape)
print('Shapes of arr5 : ',arr5.shape) 

Shapes of arr4 :  (2, 3, 4)
Shapes of arr5 :  (3, 3, 4)


In [72]:
#full fucntions
fullfun_num=np.full((3,4),34) # you type any number/string of array and also 3x4 matrox form
print(fullfun_num)
fullfun_str=np.full((4,4),'python') 
print("\n",fullfun_str)

[[34 34 34 34]
 [34 34 34 34]
 [34 34 34 34]]

 [['python' 'python' 'python' 'python']
 ['python' 'python' 'python' 'python']
 ['python' 'python' 'python' 'python']
 ['python' 'python' 'python' 'python']]


In [74]:
#arange funncation excatly work like range fucntion python
arr6=np.arange(10,21,2) #arange(start,end,diffrence) , there end is exclusive
arr6

array([10, 12, 14, 16, 18, 20])

In [76]:
arr6=np.arange(15,0,-1)
arr6

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [84]:
#linspace
arr7=np.linspace(10,20,15, dtype=int) # it have inclusive and it diveded with 15 equal parts
arr7
#logic behind dived equal parts b/w 10 to 20
#(20-10)/15-1 = 10/14 =0.71428571 and just add this number with 10 until we will not got 20 

array([10, 10, 11, 12, 12, 13, 14, 15, 15, 16, 17, 17, 18, 19, 20])

In [89]:
#covert arr7 array into matrix
mat1=arr7.reshape((3,5)) # by default its column wise show not row wise
mat1

<class 'numpy.ndarray'>


array([[10, 10, 11, 12, 12],
       [13, 14, 15, 15, 16],
       [17, 17, 18, 19, 20]])

In [88]:
mat1=arr7.reshape((3,5),order='F') # now its row wise show not column wise
mat1

array([[10, 12, 14, 16, 18],
       [10, 12, 15, 17, 19],
       [11, 13, 15, 17, 20]])

In [94]:
#covert again matrix to array
mat1_to_arr=mat1.flatten()
mat1_to_arr

array([10, 10, 11, 12, 12, 13, 14, 15, 15, 16, 17, 17, 18, 19, 20])

In [103]:
#show unique values from array
unqarr1=np.array([[2,2,6],[7,8,7]],dtype=int)
unqarr1=np.unique(unqarr1)
unqarr1

array([2, 6, 7, 8])

In [113]:
#concatinate two or more arrays
arr8=np.linspace(10,19,10,dtype=int)
arr9=np.linspace(20,29,10,dtype=int)
print(arr8,"\n",arr9)
concat=np.concatenate((arr9,arr8)) # you pass with list or tuple
print("\nConcatenate Above Array\n",concat)

[10 11 12 13 14 15 16 17 18 19] 
 [20 21 22 23 24 25 26 27 28 29]

Concatenate Above Array
 [20 21 22 23 24 25 26 27 28 29 10 11 12 13 14 15 16 17 18 19]


In [118]:
#COLUMN must be same but ROW may be diffrent also rowxcolumn must be same 
mm1=arr8.reshape((5,2))
mm2=arr9.reshape((5,2))
concat=np.concatenate([mm1,mm2])
print(concat.shape)
concat

(10, 2)


array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [129]:
#convert array to list
l1=mm1.tolist()
print(l1.__class__,"\n",l1)

<class 'list'> 
 [[10, 11], [12, 13], [14, 15], [16, 17], [18, 19]]


In [594]:
#random number geberate into array
arr10=np.random.randint(1,11,8) # (start,end,diffrence), end is exclusive
arr10

array([10,  1,  1,  5,  4,  8,  5,  5])

In [607]:
#indexing acces like in python with array
print(arr10[0],"\n",arr10[-1],"\n",arr10[-3])
print(arr10[:3],"\n",arr10[5:],"\n",arr10[2:6],"\n",arr10[2:-3])

10 
 5 
 8
[10  1  1] 
 [8 5 5] 
 [1 5 4 8] 
 [1 5 4]


In [624]:
#arr5 is 3D matrix on top where we created
arr5
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[0][2],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[7 4 6 3] 



In [625]:
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[1][2],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[9 9 3 8] 



In [627]:
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[2][0][:3],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[7 1 0] 



In [628]:
print(arr5[0],'\n\n',arr5[1],'\n\n',arr5[2],'\n\n')
print(arr5[1][0][:-1],'\n')

[[2 3 4 8]
 [9 5 3 6]
 [7 4 6 3]] 

 [[2 1 0 2]
 [4 9 8 6]
 [9 9 3 8]] 

 [[7 1 0 7]
 [0 9 8 0]
 [9 4 6 7]] 


[2 1 0] 

